development:
  adapter: postgresql
  encoding: unicode
  database: ecommcelmatix_dev
  host: localhost
  pool: 5
  username: postgres
  password: password
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: ecommcelmatix_test
  host: localhost
  pool: 5
  username: postgres
  password: password
  timeout: 5000
